### PR TITLE
Added Keva.

### PR DESCRIPTION
**Pull request by kevacoin-project**
Could you please merge the support for Kevacoin (https://kevacoin.org) RandomX variant? Thanks!

The variant has been implemented in xmrigCC:
https://github.com/Bendr0id/xmrigCC/commits/master

### CODE REVIEW

**Comment by bobbieltd** [comment]
Kevacoin is Litecoin/Bitcoin fork. 
How can you make Cryptonote repos usable tor Bitcoin forks ?

**Comment by kevacoin-project** [comment]
We modified and enhanced the bitcoin block header  so that it is compatible with Cryptonote block header. Our current  hash algorithm is Cryptonight R, but the community wants to change to a variant of RandomX to prevent the use of Nicehash.

**Comment by bobbieltd** [comment]
Thanks for info. Cool ! 
Normally, MoneroOcean follows xmrig. If you already PRed xmrig, I think he will add your algo.

**Comment by kevacoin-project** [comment]
Sorry, we may need further changes. Close for now.

**Pull request closed without merging**
