### PR TITLE
cn/2-v2 Update

### PR DESCRIPTION
**Pull request by QuantumLeaper**
Works with latest cn/2-v2 algorithm (September 23rd)

### CODE REVIEW

**Comment by bobbieltd** [comment]
Whatttt !?! Holyyyyy ! You should not copy and paste like that, only PR the cn/2 part of codes.

**Comment by QuantumLeaper** [comment]
My bad for the horrid workflow. Was in a rush :p

**Comment by MoneroOcean** [comment]
@QuantumLeaper where did you took that cn/2-v2 code from? xmrig official repo do not have cn/2 tweak, right?

**Comment by bobbieltd** [comment]
@MoneroOcean Can you add Cryptonight Lite Variant 2 (it seems not in your codes) or we need to wait for xmrig.

**Comment by MoneroOcean** [comment]
We need to wait for xmrig. I do not feel like putting effort developing it ahead.

**Comment by MoneroOcean** [comment]
Closing this since cn/2 tweak is integrated by me.

**Comment by QuantumLeaper** [comment]
My apologies for the late response. I pulled the XMRIG files from a development version of XMRIG before it was released after testing it to see it worked.

@bobbieltd I didn't know there was a cnlite variant 2 even in development, but if you link me to the code I can attempt to port it to XMRIG

**Pull request closed without merging**
