### PR TITLE
Support of CryptoNight v8 Waltz and CryptoNight v8 ReverseWaltz

### PR DESCRIPTION
**Pull request by EDDragonWolf**
Added support of two tweaks of CryptoNight hashing algorithms:
 - CryptoNight v8 Waltz (named VARIANT_WALTZ here) - equal to CryptoNight v8 but with 3/4 iterations of CryptoNight v8
 - CryptoNight v8 Reverse Waltz (named VARIANT_RWZ here) - equal to CryptoNight v8 but with 3/4 iterations of CryptoNight v8 and with reversed shuffle operation

We plan to use CryptoNight v8 Reverse Waltz as new PoW algorithm for Graft (https://github.com/graft-project/GraftNetwork/pull/234).

### CODE REVIEW

**Comment by MoneroOcean** [comment]
Thank you for PR! Will prefer to port it directly from xmrig to avoid conflicts later. Please let me know if for some reason this is not completely acceptable.

**Comment by nilhcraiv** [comment]
Hello,

CryptoNight V8 with 3/4 iterations is used by Zelerius network. It was requested to be included a month ago here -> https://github.com/MoneroOcean/node-cryptonight-hashing/pull/21 it was named it cryptonight_v8_zelerius or cryptonight_zelerius.

Are you going to merge the Zelerius PR?

Thank you

**Comment by EDDragonWolf** [comment]
@MoneroOcean, thanks for the response.
No, it is acceptable. I also understood it after investigating your change history, so we already made PR for xmrig (https://github.com/xmrig/xmrig/pull/963). Is this PR for xmrig suitable for you to add support into your library (of course, after that xmrig will review and merge it)?

**Comment by EDDragonWolf** [comment]
@nilhcraiv 
I know that you use it, however, your PR is still unresolved, so I didn't know how to work with it. We do not plan to use in the network, but I needed support for it since I wanted to make performance tests and compare Waltz (you call it cryptonight_v8_zelerius) and ReverseWaltz.

If you do not mind I can add cryptonight_v8_zelerius as separated algorithm configuration for xmrig (and here if it still needed) in our PR. However, I'm not sure that xmrig'll accept it since I did not see that it supports different aliases for the same algorithm as xmr-stak.

**Comment by nilhcraiv** [comment]
Hello @EDDragonWolf ! I think using it just for performance testing is very different than using it in a real network like the Zelerius network. Many users will look for this algorithm to mine Zelerius because it's the algorithm used by the Zelerius network but only Graft developers will use this algorithm to do performance tests. To avoid confusion for users I think the correct name should be cryptonight_v8_zelerius.

Currently, on xmr-stak it has been called "cryptonight_v8_zelerius" and SRBMiner called it "Cryptonight Zelerius", in all of them, the word Zelerius appears to avoid confusion. If xmrig can use two names for the same algorithm, come in, but if it were not I think the correct name should be "cryptonight_v8_zelerius" due to it's the algorithm used by Zelerius and Graft doesn't use it.

On the other hand, the PR is unresolved because it wasn't included and the code has changed, we can create another PR against the current code.

**Comment by MoneroOcean** [comment]
I will accept this PR as it is now (because there is same in xmrig repo and I suppose it will be likely accepted), however if xmrig will decide to do renaming here I will also follow it.

**Comment by Patrickdurbin** [comment]
@MoneroOcean https://github.com/graft-project/GraftNetwork/issues/224

All of this confusion could have been avoided 
I truly think you should mitigate for zelerius in this case.
This will keep it uniform.

Graft isn't even going to use Zelerius algo "of which they call waltz" and make code reference too in graft network as "waltz" Graft should update it to Zeleirus algo in grafts code for the calls it makes in testing as well. 2 projects made a call for zelerius.

**Pull request merged**
